### ISSUE TITLE
Fix http connection pool handling

### ISSUE THREAD

**Issue by marekhorst** [openaire/iis#1132]
When running patent retrieval communicating with remote EPO endpoint the following exceptions were logged after ~1h of processing while being throttled with rate limits:

```
20/08/11 14:25:07 ERROR PatentMetadataRetrieverJob: Failed to obtain patent metadata for patent: 9500628
org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.leaseConnection(PoolingHttpClientConnectionManager.java:316)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$1.get(PoolingHttpClientConnectionManager.java:282)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:190)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:118)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at eu.dnetlib.iis.wf.referenceextraction.patent.OpenPatentWebServiceFacade.getPatentMetadata(OpenPatentWebServiceFacade.java:124)
	at eu.dnetlib.iis.wf.referenceextraction.patent.OpenPatentWebServiceFacade.getPatentMetadata(OpenPatentWebServiceFacade.java:112)
	at eu.dnetlib.iis.wf.referenceextraction.patent.PatentMetadataRetrieverJob.getMetadataFromFacade(PatentMetadataRetrieverJob.java:173)
	at eu.dnetlib.iis.wf.referenceextraction.patent.PatentMetadataRetrieverJob.lambda$retrieveFromRemoteEndpoint$c7be745$1(PatentMetadataRetrieverJob.java:151)
	at org.apache.spark.api.java.JavaPairRDD$$anonfun$pairFunToScalaFun$1.apply(JavaPairRDD.scala:1043)
	at org.apache.spark.api.java.JavaPairRDD$$anonfun$pairFunToScalaFun$1.apply(JavaPairRDD.scala:1043)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at org.apache.spark.storage.memory.MemoryStore.putIterator(MemoryStore.scala:222)
	at org.apache.spark.storage.memory.MemoryStore.putIteratorAsValues(MemoryStore.scala:299)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1165)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1156)
	at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:1091)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1156)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:882)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:335)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:286)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1405)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Apparently the code does not close the connections properly.

Apart from `OpenPatentWebServiceFacade` also `SoftwareHeritageOriginsImporter` job communicating with external services is affected.

**Comment by marekhorst** [comment]
The solution is to rely on `CloseableHttpResponse` which is produced by `CloseableHttpClient`. It should be wrapped within `try` block to let the `close()` method being invoked at the end.
