### ISSUE TITLE
Enable DocumentClassificationJobTest

### ISSUE THREAD

**Issue by przemyslawjacewicz** [openaire/iis#1186]
`eu.dnetlib.iis.wf.documentsclassification.DocumentClassificationJobTest` is disabled after upgrading spark (PR #1020) but the reason is undocumented. We should try to enable this test or document the reason for disabling.

**Comment by przemyslawjacewicz** [comment]
Running this test locally on my machine failed:
```text
Traceback (most recent call last):
  File "/tmp/spark-c75f7551-0e3c-4b47-bbbf-5d51ac068588/userFiles-651593f4-fbed-4a99-b4ca-7777aba64f9b/scripts/madis/mexec.py", line 4, in <module>
    import functions
  File "/tmp/spark-c75f7551-0e3c-4b47-bbbf-5d51ac068588/userFiles-651593f4-fbed-4a99-b4ca-7777aba64f9b/scripts/madis/functions/__init__.py", line 8, in <module>
    import apsw
ImportError: No module named apsw
```
Running the test in Jenkins was successful. I think I've disabled this test while working on upgrading spark because I didn't have `apsw` module installed and then committed it by mistake. Anyway, I'm creating PR to restore this test.
