### ISSUE TITLE
error in communication with remote machine while checking oozie status during integration tests

### ISSUE THREAD

**Issue by marekhorst** [openaire/iis#154]
This kind of error:
```
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 227.269 sec <<< FAILURE! - in eu.dnetlib.iis.workflows.collapsers.basic.WorkflowTest
testDefaultWorkflow(eu.dnetlib.iis.workflows.collapsers.basic.WorkflowTest)  Time elapsed: 107.148 sec  <<< ERROR!
java.lang.RuntimeException: Error in communication with remote machine
	at net.schmizz.concurrent.Promise.retrieve(Promise.java:139)
	at net.schmizz.concurrent.Event.await(Event.java:103)
	at net.schmizz.sshj.connection.channel.AbstractChannel.join(AbstractChannel.java:259)
	at eu.dnetlib.iis.core.SshSimpleConnection.execute(SshSimpleConnection.java:52)
	at eu.dnetlib.iis.core.SshSimpleConnection.execute(SshSimpleConnection.java:32)
	at eu.dnetlib.iis.core.SshOozieClient.getJobStatus(SshOozieClient.java:50)
	at eu.dnetlib.iis.core.AbstractOozieWorkflowTestCase.waitForJobFinish(AbstractOozieWorkflowTestCase.java:201)
	at eu.dnetlib.iis.core.AbstractOozieWorkflowTestCase.testWorkflow(AbstractOozieWorkflowTestCase.java:134)
	at eu.dnetlib.iis.core.AbstractOozieWorkflowTestCase.testWorkflow(AbstractOozieWorkflowTestCase.java:111)
	at eu.dnetlib.iis.workflows.collapsers.basic.WorkflowTest.testDefaultWorkflow(WorkflowTest.java:18)
```

occasionally happens while checking oozie status during integration tests.

This was the cause of the failure in recent integration tests suite run:
http://ci.ceon.pl/view/IIS/job/iis_master_integration_tests_on_exp_branch/21/console

**Comment by madryk** [comment]
Looks like our frontend machine sometimes refuses to respond.
We could try to check status less often to reduce amount of traffic (I'm thinking 1 request per 10 seconds is enough).
We could also implement some retry mechanism in case of error. This should fix the problem

**Comment by marekhorst** [comment]
1 request per 10 seconds should be enough.

Let's go with retry mechanism as well.
