### ISSUE TITLE
Integration workflow test for documents-classification doesn't work on cluster

### ISSUE THREAD

**Issue by madryk** [openaire/iis#245]
Tested workflow: eu/dnetlib/iis/workflows/documentsclassification/sampletest/oozie_app/workflow.xml

Found stacktraces in logs:
16/03/11 13:31:31 ERROR yarn.ApplicationMaster: User class threw exception: Output directory /user/madryk/workflows/documentsclassification/sampletest/working_dir/documentsclassification/document_to_document_classes already exists
org.apache.hadoop.mapred.FileAlreadyExistsException: Output directory /user/madryk/workflows/documentsclassification/sampletest/working_dir/documentsclassification/document_to_document_classes already exists
	at org.apache.hadoop.mapreduce.lib.output.FileOutputFormat.checkOutputSpecs(FileOutputFormat.java:146)
	at org.apache.spark.rdd.PairRDDFunctions.saveAsNewAPIHadoopDataset(PairRDDFunctions.scala:976)
	at org.apache.spark.rdd.PairRDDFunctions.saveAsNewAPIHadoopFile(PairRDDFunctions.scala:903)
	at org.apache.spark.api.java.JavaPairRDD.saveAsNewAPIHadoopFile(JavaPairRDD.scala:781)
	at pl.edu.icm.sparkutils.avro.SparkAvroSaver.saveJavaPairKeyRDD(SparkAvroSaver.java:67)
	at pl.edu.icm.sparkutils.avro.SparkAvroSaver.saveJavaRDD(SparkAvroSaver.java:53)
	at eu.dnetlib.iis.workflows.documentsclassification.DocumentClassificationJob.main(DocumentClassificationJob.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:480)
16/03/11 13:31:31 INFO remote.RemoteActorRefProvider$RemotingTerminator: Shutting down remote daemon.

and

16/03/11 13:31:14 ERROR yarn.ApplicationMaster: User class threw exception: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3, spark-s2.vls.icm.edu.pl): ExecutorLostFailure (executor 2 lost)
Driver stacktrace:
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3, spark-s2.vls.icm.edu.pl): ExecutorLostFailure (executor 2 lost)
Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1203)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1192)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1191)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1191)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:693)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:693)
	at scala.Option.foreach(Option.scala:236)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:693)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1393)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1354)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
16/03/11 13:31:14 INFO remote.RemoteActorRefProvider$RemotingTerminator: Shutting down remote daemon.

**Comment by marekhorst** [comment]
Do reference extraction integration tests pass on cluster? If the answer is yes, then it is probably unrelated to python's apsw library. 

Anyway if no detailed outcome is provided in logs then it could be related to Madis as it tends to swallow such informations and it could be retrieved from user logs.

**Comment by madryk** [comment]
Yes. Reference extraction tests passes.
