### ISSUE TITLE
CDH5 documents classification spark tests fail after merging changes from master

### ISSUE THREAD

**Issue by marekhorst** [openaire/iis#311]
Problem occurs while running tests from `DocumentClassificationJobTest`.

According to surfire reports option `-o pipefail` added in #282 is illegal:
```
/tmp/spark-e3cd14f3-30f5-4238-92db-cb3cbf3676db/userFiles-7d71154b-3216-4302-879d-1810d92421a3/scripts/classify_documents.sh: 2: set: Illegal option -o pipefail
```

**Comment by marekhorst** [comment]
After reverting #282 change another error occurs:
```
ERROR TaskSetManager: Task 0 in stage 0.0 failed 1 times; aborting job
/tmp/spark-830585bc-3727-4606-9bc1-59e1cb70dcc0/userFiles-dd025d18-d805-4d97-9579-d7029f1a6323/scripts/classify_documents.sh: 3: /tmp/spark-830585bc-3727-4606-9bc1-59e1cb70dcc0/userFiles-dd025d18-d805-4d97-9579-d7029f1a6323/scripts/classify_documents.sh: scripts/complete_taxonomies.py: not found
/tmp/spark-830585bc-3727-4606-9bc1-59e1cb70dcc0/userFiles-dd025d18-d805-4d97-9579-d7029f1a6323/scripts/classify_documents.sh: 3: /tmp/spark-830585bc-3727-4606-9bc1-59e1cb70dcc0/userFiles-dd025d18-d805-4d97-9579-d7029f1a6323/scripts/classify_documents.sh: scripts/madis/mexec.py: not found
16/04/09 00:24:59 ERROR Executor: Exception in task 0.0 in stage 0.0 (TID 0)
java.lang.Exception: Subprocess exited with status 127
        at org.apache.spark.rdd.PipedRDD$$anon$1.hasNext(PipedRDD.scala:161)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$12.apply(PairRDDFunctions.scala:998)
        at org.apache.spark.rdd.PairRDDFunctions$$anonfun$12.apply(PairRDDFunctions.scala:979)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:61)
        at org.apache.spark.scheduler.Task.run(Task.scala:64)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:203)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by mpol** [comment]
`DocumentClassificationJob` runs the script explicitly with `sh`, no wonder a `bash` option does not work :-(

**Comment by marekhorst** [comment]
True, can't we use `bash` instead? 

We should also fix `classify_documents.sh` by executing `python` command explicitly and reintroducing parameterized paths:
```
python $1/madis/mexec.py -d $1/taxonomies.db -f $1/classify.sql | python $1/complete_taxonomies.py
```
instead of version merged from `master` branch:
```
scripts/madis/mexec.py -d scripts/taxonomies.db -f scripts/classify.sql | scripts/complete_taxonomies.py
```

**Comment by mpol** [comment]
@lukdumi Pull request #312 changes `sh` to `bash`. Does it work on Windows?

**Comment by lukdumi** [comment]
@mpol Yes, it does :-)
