### ISSUE TITLE
Check and correct problems with ssh connection during int tests

### ISSUE THREAD

**Issue by lukdumi** [openaire/iis#315]

**Comment by madryk** [comment]
It fails when running primary test workflow

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 469.951 sec <<< FAILURE! - in eu.dnetlib.iis.wf.primary.processing.WorkflowTest
testIntegrationMainChainWorkflow(eu.dnetlib.iis.wf.primary.processing.WorkflowTest)  Time elapsed: 469.949 sec  <<< ERROR!
java.lang.RuntimeException: Error in opening ssh connection
	at net.schmizz.sshj.SSHClient.auth(SSHClient.java:217)
	at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:316)
	at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:365)
	at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:295)
	at eu.dnetlib.iis.common.SshSimpleConnection.openConnection(SshSimpleConnection.java:99)
	at eu.dnetlib.iis.common.SshConnectionManager.getConnection(SshConnectionManager.java:49)
	at eu.dnetlib.iis.common.SshOozieClient.getJobStatus(SshOozieClient.java:48)
	at eu.dnetlib.iis.common.AbstractOozieWorkflowTestCase.waitForJobFinish(AbstractOozieWorkflowTestCase.java:204)
	at eu.dnetlib.iis.common.AbstractOozieWorkflowTestCase.testWorkflow(AbstractOozieWorkflowTestCase.java:137)
	at eu.dnetlib.iis.wf.primary.processing.WorkflowTest.testIntegrationMainChainWorkflow(WorkflowTest.java:24)
