### ISSUE TITLE
Master integration tests failure due to SSH communication error

### ISSUE THREAD

**Issue by marekhorst** [openaire/iis#328]
Strangely it fails on the very last integration test from whole suite: `eu.dnetlib.iis.workflows.top.WorkflowTest#testIntegrationMainChainWorkflow()`.
this is also the most complex one.

It has been failing with the same error message for last 2 consecutive executions:
http://ci.ceon.pl/view/IIS/job/iis_master_integration_tests/125/console
http://ci.ceon.pl/view/IIS/job/iis_master_integration_tests/126/console

Stacktrace:
```
java.lang.RuntimeException: Error in communication with remote machine: Timeout expired
	at net.schmizz.concurrent.Promise.retrieve(Promise.java:139)
	at net.schmizz.concurrent.Event.await(Event.java:103)
	at net.schmizz.sshj.connection.channel.AbstractChannel.close(AbstractChannel.java:245)
	at eu.dnetlib.iis.core.SshSimpleConnection.executeCommand(SshSimpleConnection.java:169)
	at eu.dnetlib.iis.core.SshSimpleConnection.executeCommandWithRetries(SshSimpleConnection.java:126)
	at eu.dnetlib.iis.core.SshSimpleConnection.execute(SshSimpleConnection.java:60)
	at eu.dnetlib.iis.core.SshSimpleConnection.execute(SshSimpleConnection.java:44)
	at eu.dnetlib.iis.core.SshOozieClient.getJobStatus(SshOozieClient.java:50)
	at eu.dnetlib.iis.core.AbstractOozieWorkflowTestCase.waitForJobFinish(AbstractOozieWorkflowTestCase.java:201)
	at eu.dnetlib.iis.core.AbstractOozieWorkflowTestCase.testWorkflow(AbstractOozieWorkflowTestCase.java:134)
	at eu.dnetlib.iis.workflows.top.WorkflowTest.testIntegrationMainChainWorkflow(WorkflowTest.java:31)
```

**Comment by mpol** [comment]
Reconfigured CI to run the test later at night. Observing. Seems not to hit the timeout for now.
