### ISSUE TITLE
Fuzzy citation matching fails with connection refused exception

### ISSUE THREAD

**Issue by marekhorst** [openaire/iis#461]
The following error is found in logs:
```
16/06/05 06:36:41 ERROR RetryingBlockFetcher: Exception while beginning fetch of 1 outstanding blocks (after 3 retries)
java.io.IOException: Failed to connect to eos-m2-sn01.ocean.icm.edu.pl/10.19.65.101:58146
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:193)
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:156)
	at org.apache.spark.network.netty.NettyBlockTransferService$$anon$1.createAndStart(NettyBlockTransferService.scala:88)
	at org.apache.spark.network.shuffle.RetryingBlockFetcher.fetchAllOutstanding(RetryingBlockFetcher.java:140)
	at org.apache.spark.network.shuffle.RetryingBlockFetcher.access$200(RetryingBlockFetcher.java:43)
	at org.apache.spark.network.shuffle.RetryingBlockFetcher$1.run(RetryingBlockFetcher.java:170)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused: eos-m2-sn01.ocean.icm.edu.pl/10.19.65.101:58146
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:224)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:289)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	... 1 more
```
Link to log file:
http://iis-cdh5-test-m3.ocean.icm.edu.pl:19888/jobhistory/logs/eos-m2-sn07.ocean.icm.edu.pl:8041/container_e29_1464942752091_0673_01_000213/container_e29_1464942752091_0673_01_000213/marek.horst

Link to spark job overview:
http://iis-cdh5-test-m3.ocean.icm.edu.pl:18088/history/application_1464942752091_0673/1/jobs/

**Comment by marekhorst** [comment]
I can also confirm this problem shows up when running fuzzy citation matching in isolation (not as a part of primary workflow).

**Comment by marekhorst** [comment]
Problem was already reported in:
https://issues.apache.org/jira/browse/SPARK-9591
and:
https://issues.apache.org/jira/browse/SPARK-7703

We managed to overcome this problem by adjusting memory and cores configuration in #472.

**Comment by marekhorst** [comment]
#472 was merged with `cdh5` branch.
