### ISSUE TITLE
Fuzzy citation matching fails with NoSuchElementException when converting citations

### ISSUE THREAD

**Issue by marekhorst** [openaire/iis#474]
Link to logs:

http://iis-cdh5-test-m3.ocean.icm.edu.pl:19888/jobhistory/logs/eos-m2-sn37.ocean.icm.edu.pl:8041/container_e29_1464942752091_1517_01_000078/container_e29_1464942752091_1517_01_000078/marek.horst

Exception stack trace:
```
16/06/08 23:19:30 ERROR Executor: Exception in task 446.2 in stage 20.0 (TID 5185)
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:313)
	at scala.None$.get(Option.scala:311)
	at eu.dnetlib.iis.wf.citationmatching.ReferenceMetadataInputConverter.lambda$convertCitations$c85f815d$1(ReferenceMetadataInputConverter.java:51)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$3$1.apply(JavaRDDLike.scala:146)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$3$1.apply(JavaRDDLike.scala:146)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at org.apache.spark.util.collection.ExternalSorter.insertAll(ExternalSorter.scala:217)
	at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:74)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
	at org.apache.spark.scheduler.Task.run(Task.scala:88)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by madryk** [comment]
It looks like algorithm is failing when rawText of reference is blank.
We probably need to update condition in `ReferenceMetadataToMatchableConverter` - `refMetadata.getRawText() != null` to `StringUtils.isNotBlank(refMetadata.getRawText())`
