### ISSUE TITLE
Fuzzy citation matching input transformers fails with TimeoutException

### ISSUE THREAD

**Issue by marekhorst** [openaire/iis#490]
The following exceptions are thrown:

```
Caused by: java.util.concurrent.TimeoutException: Futures timed out after [120 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:107)
	at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:169)
	at scala.concurrent.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3640)
	at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread.blockOn(ThreadPoolBuilder.scala:167)
	at scala.concurrent.Await$.result(package.scala:107)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcEnv.scala:241)
```
Full log is available here:
http://iis-cdh5-test-m3.ocean.icm.edu.pl:19888/jobhistory/logs/eos-m2-sn04.ocean.icm.edu.pl:8041/container_e29_1464942752091_2215_01_000001/container_e29_1464942752091_2215_01_000001/marek.horst/stdout/?start=0

This failure happens occasionally.

**Comment by marekhorst** [comment]
The possible reason are too many executors (over 500) and simple tests where number of executors was limited (in the very same way as it was done in #472) proved no such problem occurs when dealing with ~170 executors.
