### ISSUE TITLE
sentiment analysis module throws NumberFormatException

### ISSUE THREAD

**Issue by marekhorst** [openaire/iis#92]
Apparently in some contents (Europe PMC in particular) position number may exceed `Integer` size:
```
java.lang.NumberFormatException: For input string: "323335374044"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
	at java.lang.Integer.parseInt(Integer.java:461)
	at java.lang.Integer.parseInt(Integer.java:499)
	at pl.edu.icm.cermine.bibref.sentiment.CitationPositionFinder.findByNumber(CitationPositionFinder.java:187)
	at pl.edu.icm.cermine.bibref.sentiment.CitationPositionFinder.findReferences(CitationPositionFinder.java:44)
	at pl.edu.icm.cermine.ExtractionUtils.findCitationPositions(ExtractionUtils.java:524)
	at pl.edu.icm.cermine.ContentExtractor.getCitationPositions(ContentExtractor.java:216)
	at pl.edu.icm.cermine.ContentExtractor.getCitationSentiments(ContentExtractor.java:229)
	at eu.dnetlib.iis.workflows.sentimentanalysis.SentimentAnalyzer.map(SentimentAnalyzer.java:46)
	at eu.dnetlib.iis.workflows.sentimentanalysis.SentimentAnalyzer.map(SentimentAnalyzer.java:30)
```

The problem is this one is unchecked exception which leads to whole processing interruption. It will be probably better to catch it inside sentiment analysis module and throw declared `AnalysisException` I could handle in wrapper.

For debugging purposes I could add text content logging to see whole document source. What do you think?

**Comment by marekhorst** [comment]
I've just committed simple patch mitigating this issue https://github.com/openaire/iis/commit/fd836a8b69aaa7f4f381ea949e35fd385da8704d so we could skip publications with invalid reference numbers.

**Comment by dtkaczyk** [comment]
I committed a bugfix for this today. I corrected the regexps, so that such "numbers" are not matched. I also added exception handling to the code, and this exception should not appear on the outside anymore.

**Comment by marekhorst** [comment]
OK, just to keep track of commits, patch was applied on CERMINE:

https://github.com/CeON/CERMINE/commit/d34a2f3de2e0a6c38c604deb72ae9723e3e307f4

I am closing this issue then.
