### ISSUE TITLE
Documents classification fails with SparkException after upgrading CDH cluster to 5.16.2

### ISSUE THREAD

**Issue by marekhorst** [openaire/iis#984]
The following exception is thrown when executing documents classification algorithm on IIS cluster after upgrading CDH version to 5.16.2:

```
org.apache.spark.SparkException: File ./scripts exists and does not match contents of hdfs://nameservice1/user/marek.horst/wf/primary/processing/sampledataproducer/oozie_app/primary_processing/documentsclassification/lib/scripts
at org.apache.spark.util.Utils$.copyFile(Utils.scala:495)
at org.apache.spark.util.Utils$.fetchFile(Utils.scala:393)
at org.apache.spark.executor.Executor$$anonfun$org$apache$spark$executor$Executor$$updateDependencies$3.apply(Executor.scala:442)
at org.apache.spark.executor.Executor$$anonfun$org$apache$spark$executor$Executor$$updateDependencies$3.apply(Executor.scala:439)
at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:772)
at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:98)
at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:98)
at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:226)
at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:39)
at scala.collection.mutable.HashMap.foreach(HashMap.scala:98)
at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:771)
at org.apache.spark.executor.Executor.org$apache$spark$executor$Executor$$updateDependencies(Executor.scala:439)
at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:221)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
```

**Comment by marekhorst** [comment]
After inspecting `DocumentClassificationJob` class and removing the following line:

https://github.com/openaire/iis/blob/4a896ca90c761a136cf40602fe746e66af5b77d2/iis-wf/iis-wf-documentsclassification/src/main/java/eu/dnetlib/iis/wf/documentsclassification/DocumentClassificationJob.java#L63

exception is not being thrown anymore. Possibly after the upgrade there is no need to add scripts directory anymore. Integration test needs to be triggered in order to confirm this solves the problem.

**Comment by marekhorst** [comment]
We also need to take an eye on:

https://github.com/openaire/iis/blob/4a896ca90c761a136cf40602fe746e66af5b77d2/iis-common/src/main/java/eu/dnetlib/iis/common/spark/pipe/SparkPipeMapReduce.java

where the similar function is being called in order to add script resources.

**Comment by przemyslawjacewicz** [comment]
Note: when using spark 2 for spark jobs in document classification changes related to this issue had to be reverted. This seems to be connected with a way in which spark 2 was introduced into cluster e.g. through custom oozie sharelib specification for spark action. An ultimate test for this configuration will be during first primary workflow run after accepting #1021.

This issue is related with #1020.
