### ISSUE TITLE
Affiliation matching fails with java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by marekhorst** [openaire/iis#987]
After upgrading CDH cluster from `5.9.0` to `5.16.2` version the following exception is thrown by executor when running affiliation matching algorithm on beta contents:
```
java.lang.NoSuchMethodError: org.apache.commons.lang3.StringUtils.removePattern(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
        at eu.dnetlib.iis.wf.affmatching.normalize.OrganizationNameNormalizer.normalize(OrganizationNameNormalizer.java:49)
        at eu.dnetlib.iis.wf.affmatching.normalize.AffMatchOrganizationNormalizer.normalize(AffMatchOrganizationNormalizer.java:48)
        at eu.dnetlib.iis.wf.affmatching.AffMatchingService.lambda$matchAffiliations$4e1c0c29$1(AffMatchingService.java:87)
        at org.apache.spark.api.java.JavaPairRDD$$anonfun$toScalaFunction$1.apply(JavaPairRDD.scala:1015)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
        at scala.collection.Iterator$$anon$14.hasNext(Iterator.scala:389)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:126)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
        at org.apache.spark.scheduler.Task.run(Task.scala:89)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:242)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```
Clearly we dealing with `commons-lang3` dependency version mismatch.

**Comment by marekhorst** [comment]
After inspecting `commons-lang3` dependencies coming from oozie package and cluster environment (cloudera parcels and oozie sharelib) it turned we are dealing with version mismatch between library provided in oozie package (IIS dependency):
```
/data/2/yarn/nm/usercache/marek.horst/appcache/application_1568627807826_1279/container_e64_1568627807826_1279_01_000001/commons-lang3-3.5.jar
```
 and oozie sharelib:
```
/data/2/yarn/nm/usercache/marek.horst/appcache/application_1568627807826_1279/container_e64_1568627807826_1279_01_000001/commons-lang3-3.3.2.jar
```
However this is not the cause of the error because:
```
org.apache.commons.lang3.StringUtils.removePattern(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
```
method was available since `3.2` version:
https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#removePattern-java.lang.String-java.lang.String-

**Comment by marekhorst** [comment]
In order to know the origin (jar package location) of a class loaded by classloader the following spark input parameters can be set:
```
--conf spark.executor.extraJavaOptions=-verbose:class --conf spark.driver.extraJavaOptions=-verbose:class
```
among `spark-opts` element in `workflow.xml` file. 

After deeper inspection it turned the `org.apache.commons.lang3.StringUtils` class originated from fat `hive-exec.jar` being part of oozie sharelib. It includes a number of shaded dependencies including `commons-lang3`.

According to `META-INF` notes shaded `commons-lang3` version was `3.1`, so before introducing `removePattern()` method. Mystery solved.

**Comment by marekhorst** [comment]
One way to cope with similar issues is to set either `spark.driver.userClassPathFirst` or `spark.executor.userClassPathFirst` to `true` (default is `false`).

According to [docs](https://spark.apache.org/docs/latest/configuration.html):
> (Experimental) Whether to give user-added jars precedence over Spark's own jars when loading classes in the driver. This feature can be used to mitigate conflicts between Spark's dependencies and user dependencies. It is currently an experimental feature. This is used in cluster mode only.

In our case the error is thrown by executor. Unfortunately setting `spark.executor.userClassPathFirst` to `true` did not solve the problem.

**Comment by marekhorst** [comment]
Again, for the record: trying with setting bunch of other properties namely:
* `oozie.launcher.mapreduce.user.classpath.first` 
* `oozie.launcher.mapreduce.job.user.classpath.first`
* `oozie.launcher.mapreduce.task.classpath.user.precedence`
* `mapreduce.job.user.classpath.first`
* `mapreduce.task.classpath.user.precedence`

set to `true` value among `global` workflow properties. This approach didn't solve the problem. 

One possible cause this solution does not work could be the fact we are relying on an automated jars resolution supported by oozie which might not be covered with precedence feature. Application jar package provided in `jar` element within `spark` action contains reference to a slim `${oozieTopWfApplicationPath}/lib/iis-wf-affmatching-${projectVersion}.jar` while other references are automatically resolved from workflow's `lib` subdirectory.

**Comment by marekhorst** [comment]
One identical issue was reported on [stackoverflow](https://stackoverflow.com/questions/48717343/user-lib-jar-precedence-over-oozie-share-lib-in-spark-action).

**Comment by marekhorst** [comment]
There is one nice oozie feature we could take advantage of in our case:

https://issues.apache.org/jira/browse/OOZIE-1624

> Sharelib may bring some jar which might conflict with user jars.
> Ex. Sharelib hive has json-2.xxxx.jar, where as some of the user use-case need higher version of json jar.
> He should be able to exclude sharelib json jar and bring his own version.

The problem is this feature was introduced in `5.2.0` oozie version while we are relying on `4.1.0` provided by `cdh5.16.2`.

**Comment by marekhorst** [comment]
Since for now I was unable to find any working solution allowing us to exclude fat `hive-exec.jar` dependency (introducing bunch of shaded classes coming from external libraries) programmatically and not affecting whole cluster I guess the viable solutions can be narrowed down to either:
* removing `hive-exec.jar` from sharelib in HDFS

or:
* aligning affiliation matching code to be compatible with `commons-lang3` `3.1` version.

For now let's leave the rationale behind the existence of malicious `hive-exec.jar` among spark sharelibs aside. Removing it from sharelib is risky as it may introduce unexpected regression in other modules running on our cluster and whenever sharelib gets rebuilt in future this nasty dependency will be reintroduced.

The second option is kind of a workaround for this problem as we might still stuck on similar issue in future in other place by referencing class which could be resolved from `hive-exec.jar` instead of the intended jar package. 
After inspecting the affiliation matching code it seems `org.apache.commons.lang3.StringUtils.removePattern()` is referenced only in 3 places and the method itself is a simple 1-liner relying on `java.util.regex.Pattern` so we can easily introduce our own version of `removePattern()` within our codebase. The major advantage of this solution: it will be quite easy to apply and will let us make IIS be fully functional again which is quite crucial for now. Meanwhile we could look for a better solution...
